### ISSUE TITLE
JSON parse error with Jsoup causing Unterminated string error with Gson

### ISSUE THREAD

**Issue by jeyalee** [Ezwen/bandcamp-collection-downloader#11]
Hi!
So I tested with my bandcamp collection and kept getting `com.google.gson.stream.MalformedJsonException: Unterminated string` error. I tracked it down to this specific title that was causing the issue.

```json
{"file": {"mp3-v0":"https://bandcamp.com/stream_redirect?enc=mp3-v0&amp;track_id=29128347&amp;ts=1600090813&amp;t=c21a41cbc124d5fdc21d23b2a802655368fc5ccb"},"title":"増&gt;&gt;&gt;&gt;減&lt;&lt;&lt;
```

I updated the connect method to return a ` Connection.Response?` and then passed the `body()` to Gson and everything was working as expected. I have the PR ready.

**Comment by Ezwen** [comment]
Fixed by #12
