### ISSUE TITLE
Built version of bandcamp-collection-downloader.jar?

### ISSUE THREAD

**Issue by cmdcolin** [Ezwen/bandcamp-collection-downloader#15]
Hi there

Just wondering if you have posted the bandcamp-collection-downloader.jar on any release page?

I managed to for example download gradle, run gradle fatjar, but wondering how to make it easier for others to use if the jar could be made available?

**Comment by Ezwen** [comment]
Hi! No I haven't properly published the jar anywhere, but maybe now would be a good time to consider it :). I'll think about it and let you know.

**Comment by Ezwen** [comment]
There is now a proper "releases" page available here: https://framagit.org/Ezwen/bandcamp-collection-downloader/-/releases

Each release comes with an executable jar which should work out of the box!

Thanks for the suggestion :)
