### ISSUE TITLE
malformed zip error

### ISSUE THREAD

**Issue by igvr** [Ezwen/bandcamp-collection-downloader#17]
```
[pool-1-thread-6] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-6] Retrying (1/3).
[pool-1-thread-6] "Levante" (2020) by Stelios Vassiloudis successfully downloaded.
```

does this mean it succeeded?

also, THANK YOU for this...
it is incredible that this is not a feature of bandcamp itself.

**Comment by Ezwen** [comment]
> does this mean it succeeded?

Yes, as you can see it first failed, then retried, then was successful. You should be able to find your music in your download folder. If not, drop another comment.

> also, THANK YOU for this...
> it is incredible that this is not a feature of bandcamp itself.

I still wonder myself why there is no official tool to do that! Glad my few lines of code are useful to you!

**Comment by craig-lofigames** [comment]
Sorry to be that guy, but I've had the issue crop up today. Very strange considering I've previously used this tool lots with no issues.

`
Connecting to Bandcamp?
Found "ctinney94's collection | Bandcamp" with 128 items.
Ignoring 124 already downloaded items (based on 'C:\Users\morty\Music\bandcamp-collection-downloader.cache').
------------
[pool-1-thread-1] Managing item 1/4
[pool-1-thread-2] Managing item 2/4
[pool-1-thread-4] Managing item 4/4
[pool-1-thread-3] Managing item 3/4
[pool-1-thread-4] Found release "Forged in Frost" (0000) by Desolation Plains (Bandcamp ID: c1708093588).
[pool-1-thread-2] Found release "Welcome Freya" (0000) by Merry Prairie (Bandcamp ID: c876770554).
[pool-1-thread-3] Found release "Of Feather and Bone - Sulfuric Disintegration" (2020) by Desiccated Productions (Bandcamp ID: p145231638).
[pool-1-thread-3] Could not download item: No URL found for item (maybe the release has no digital item, or the provided download format is invalid)
[pool-1-thread-1] Found release "Finale" (0000) by Desolation Plains (Bandcamp ID: c2269307232).
[pool-1-thread-4] Starting the download of "Forged in Frost" (0000) by Desolation Plains.
[pool-1-thread-2] Starting the download of "Welcome Freya" (0000) by Merry Prairie.
[pool-1-thread-1] Starting the download of "Finale" (0000) by Desolation Plains.
[pool-1-thread-4] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-4] Retrying (1/3).
[pool-1-thread-2] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-2] Retrying (1/3).
[pool-1-thread-1] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-1] Retrying (1/3).
[pool-1-thread-4] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-4] Retrying (2/3).
[pool-1-thread-1] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-1] Retrying (2/3).
[pool-1-thread-2] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-2] Retrying (2/3).
[pool-1-thread-4] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-4] Retrying (3/3).
[pool-1-thread-2] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-2] Retrying (3/3).
[pool-1-thread-1] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-1] Retrying (3/3).
[pool-1-thread-4] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-4] Could not download item: Could not perform task after 3 retries.
[pool-1-thread-1] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-1] Could not download item: Could not perform task after 3 retries.
[pool-1-thread-2] Error while trying: "org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: zip END header not found".
[pool-1-thread-2] Could not download item: Could not perform task after 3 retries.`

The folder was created but not populated with any files
