### ISSUE TITLE
Support for cookies.txt format?

### ISSUE THREAD

**Issue by cmdcolin** [Ezwen/bandcamp-collection-downloader#5]
Hi there
I am not getting the auto-cookie-finding from firefox to work and the extension is spitting out cookies that might have blanked out values for privacy? kind of unclear

I was wondering if you could support cookies.txt format like curl or like https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en outputs

I tried converting the cookies.txt to json but saw that it was expecting some specific fields that I wasn't getting
Thanks

**Comment by cmdcolin** [comment]
I think I managed to get the output from the Firefox extension to work actually

I was confused by the values in the cookies.json like

	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",

And maybe thought I wasn't getting like the right cookies or something, but then I saw in the source code that it only looks at name_raw and content_raw

Still might be cook to get the cookies.txt :)

**Comment by Ezwen** [comment]
Thanks for the idea! Indeed supporting the cookies.txt format sound reasonnable. When I have time I can look into java parsers that can work with such things. And of course PRs are welcome if you want to take a look at it yourself :)
